### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by PreviousTlx** [leancloud/LeanCloudChatKit-Android#80]
设备 GI-I9500_TMMARS
版本 5.1
在使用的途中，出现了一下错误，详细日志在下面，因为上面的都是一样的，所以我就截取了后面一些错误信息。可能是因为某些问题，重复执行了某个方法，导致crash。目前就仅仅是这个设备出现了问题。在日志底部的信息是指向avoscloud这个类里面。谢谢！
java.lang.StackOverflowError: stack size 1036KB at com.google.protobuf.TextFormat$TextGenerator.<init>(Unknown Source) 

	at java.lang.reflect.Method.invoke(Method.java:394)
	at com.google.protobuf.GeneratedMessageV3.invokeOrDie(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.access$1100(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.has(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.hasField(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.getAllFieldsMutable(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.getAllFields(Unknown Source)
	at com.google.protobuf.TextFormat$Printer.print(Unknown Source)
	at com.google.protobuf.TextFormat$Printer.access$000(Unknown Source)
	at com.google.protobuf.TextFormat.print(Unknown Source)
	at com.google.protobuf.TextFormat.printToString(Unknown Source)
	at com.google.protobuf.AbstractMessage.toString(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:394)
	at com.google.protobuf.GeneratedMessageV3.invokeOrDie(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.access$1100(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.has(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.hasField(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.getAllFieldsMutable(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.getAllFields(Unknown Source)
	at com.google.protobuf.TextFormat$Printer.print(Unknown Source)
	at com.google.protobuf.TextFormat$Printer.access$000(Unknown Source)
	at com.google.protobuf.TextFormat.print(Unknown Source)
	at com.google.protobuf.TextFormat.printToString(Unknown Source)
	at com.google.protobuf.AbstractMessage.toString(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:394)
	at com.google.protobuf.GeneratedMessageV3.invokeOrDie(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.access$1100(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.has(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.hasField(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.getAllFieldsMutable(Unknown Source)
	at com.google.protobuf.GeneratedMessageV3.getAllFields(Unknown Source)
	at com.google.protobuf.TextFormat$Printer.print(Unknown Source)
	at com.google.protobuf.TextFormat$Printer.access$000(Unknown Source)
	at com.google.protobuf.TextFormat.print(Unknown Source)
	at com.google.protobuf.TextFormat.printToString(Unknown Source)
	at com.google.protobuf.AbstractMessage.toString(Unknown Source)
	at com.avos.avoscloud.AVPushWebSocketClient.send(Unknown Source)
	at com.avos.avoscloud.AVPushConnectionManager.loginCmd(Unknown Source)
	at com.avos.avoscloud.AVPushWebSocketClient.onOpen(Unknown Source)
	at org.java_websocket.client.WebSocketClient.onWebsocketOpen(Unknown Source)
	at org.java_websocket.WebSocketImpl.open(Unknown Source)
	at org.java_websocket.WebSocketImpl.decodeHandshake(Unknown Source)
	at org.java_websocket.WebSocketImpl.decode(Unknown Source)
	at org.java_websocket.client.WebSocketClient.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:818)

**Comment by PreviousTlx** [comment]
对了，忘记补充了，是v4.7.9的版本。
